apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iidt2kbb8-java-springboot 
  janus-idp.io/tekton: iidt2kbb8-java-springboot
  backstage.io/kubernetes-id: iidt2kbb8-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iidt2kbb8-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml