apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: iidt2kbb8-java-springboot-gitops-repository
spec:
  url: https://github.com/sjm-rhtap/iidt2kbb8-java-springboot-gitops